version: "1.0"
services:
    postgres:
        restart: always
        build: ./postgres
        volumes:
            - type: volume
              source: harley-db
              target: /var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=${pg_password}
    bot:
        restart: always
        build: .
        depends_on:
            - postgres
        command: ["./wait-for-it.sh", "postgres:5432", "--", "python", "main.py"]
volumes:
    harley-db: