version: "3.8"
services:
    postgres:
        restart: always
        build: ./postgres
        volumes:
            - type: volume
              source: harley-db
              target: /var/lib/postgresql/data
        env_file:
            - "./.env"
    bot:
        restart: always
        env_file:
            - "./.env"
        build: .
        depends_on:
            - postgres
        command:
            [
                "./wait-for-it.sh",
                "postgres:5432",
                "--",
                "poetry",
                "run",
                "python",
                "main.py"
            ]
volumes:
    harley-db: null
